name: isolate_generator
description: flutter and dart code generator package for generating Isolate code for your classes.
version: 0.0.5+2
repository: https://github.com/7mada123/isolate_generator

platforms:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  isolate_generator_annotation:
    path: ../isolate_generator_annotation

  build: ">=2.3.1 < 3.0.0"
  source_gen: ">=1.2.6 < 2.0.0"
  analyzer: ">=5.2.0 < 6.0.0"

dev_dependencies:
  lints: ">=2.0.1 < 3.0.0"
  build_runner: ">= 2.3.2 < 3.0.0"